language: ruby
dist: trusty
cache: bundler
sudo: false
rvm:
  - 2.4
  - 2.5
before_install:
  - gem update --system
  - gem update --remote bundler
  - gem --version
  - gem install bundler
  - bundle --version
branches:
  only:
    - master
env:
  global:
    - CC_TEST_REPORTER_ID=b32bade44482d3debfa79056a4843ba58c77802d3fb5d358be90692389eec70a
jobs:
  include:
    - stage: test
      script: bundle exec rake rubocop
    - stage: test
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: bundle exec rake spec
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: build
      script: bundle exec rake build
    - stage: gem release
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        gem: cpp_dependency_graph
        on:
          tags: true
        api_key:
          secure: oIzNdzho4Jb3/I9PCjpTpWnlPky00sqVSFtPKz0GPe4XE+nvPymX8ZSbnboHshVjI/4bYkxZPyaa8cjYsdpSzFFEiCM/6T6tWQpualpfXQ/dLsaj4Nlw2GGGfIm3XcL2aEbO9zfc2sroy7Hdy6lL9vZw/sm2YaN4dxn1PwIcgQqsNL4WTuFdejPHk02Lp1cbGcvNhA6GkuNigg0R1x+heEPetL9wL2JW/uEak12o8RgEG/3+AQbw290OCFi4x80ig/StOzmkCgcCMgcOhURfNgsJaXJxjjK/+6eWw/jAv1KG5cqQ8SnOeJUwx4xXu22hO645UUunx0U+qte+ay2RoL95/veD1FZc3FtYwSphzhGKhvlGspW/FlqC8U0TVSRWJFNobZDxHM7iYiK4OB9yTeGKIC/poZMZ5a9Ht4wqISuGa9wBmXtXhKvqfvQ1nrHc1J9bZj4p20DhY1V4JXPlExWXbZLzlXxTeBSKsjH/WGUdho9DpdJPMyiSGOv/YYWdUuUvW+xm8qQ/dRHaiKHRsOdOB9QoIIXUPF2hVN2SplK5cImLQw7KW+DeQFVgqHsdPVDfpjCtMTeDhwxlfHncf5+8nslnNRWOvn0eGZ5vp86NkfNLXOG+JgcptrucUK/6q1hRqFOLHSETOzpgTzQujNhGihMZYsG1QehXasDYxDg=
